/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'total' : bigint,
  'paymentMethod' : string,
  'deliveryFee' : bigint,
  'customerPhone' : string,
  'createdAt' : bigint,
  'customerAddress' : string,
  'items' : Array<OrderItem>,
  'subtotal' : bigint,
}
export interface OrderItem {
  'size' : string,
  'productId' : bigint,
  'productName' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export interface Product {
  'id' : bigint,
  'imageUrls' : Array<string>,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'sizes' : Array<string>,
  'availability' : boolean,
  'category' : string,
  'price' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addProduct' : ActorMethod<
    [string, bigint, string, Array<string>, string, Array<string>, boolean],
    bigint
  >,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getContactInfo' : ActorMethod<[], string>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getOrders' : ActorMethod<[string], Array<Order>>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getReturnPolicy' : ActorMethod<[], string>,
  'initialize' : ActorMethod<[], undefined>,
  'isInitializedQuery' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [string, string, string, Array<OrderItem>, string],
    bigint
  >,
  'updateOrderStatus' : ActorMethod<[bigint, string, string], undefined>,
  'updateProduct' : ActorMethod<
    [
      bigint,
      string,
      bigint,
      string,
      Array<string>,
      string,
      Array<string>,
      boolean,
    ],
    undefined
  >,
  'verifyAdminPassword' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];